from database.base import init_db
from database.requests import (
    add_user,
    create_feedback,
    create_news,
    create_school_class,
    delete_school_class_if_empty,
    get_active_class_grades,
    get_active_classes_by_grade,
    get_active_users,
    get_all_users,
    get_class_by_grade_letter,
    get_class_by_id,
    get_feedbacks_list,
    get_user_feedback_by_id,
    get_user_feedbacks,
    get_news_by_id,
    get_news_count,
    get_news_list,
    get_user_by_tg_id,
    get_users_count_by_class,
    update_user_profile,
    update_user_role,
    update_user_status,
)

__all__ = [
    "init_db",
    "get_user_by_tg_id",
    "get_all_users",
    "get_active_users",
    "add_user",
    "update_user_profile",
    "update_user_role",
    "update_user_status",
    "create_news",
    "get_news_list",
    "get_news_count",
    "get_news_by_id",
    "create_feedback",
    "get_feedbacks_list",
    "get_user_feedbacks",
    "get_user_feedback_by_id",
    "get_active_class_grades",
    "get_active_classes_by_grade",
    "get_class_by_id",
    "get_class_by_grade_letter",
    "create_school_class",
    "get_users_count_by_class",
    "delete_school_class_if_empty",
]


